### ISSUE TITLE
Lab1:Write Stakeholders Needs

### ISSUE THREAD

**Issue by serrhiy** [serrhiy/database-course-work#22]

**Comment by serrhiy** [comment]
@gloviee finish this file please

**Comment by gloviee** [comment]
writed

**Comment by serrhiy** [comment]
@gloviee you have changed wrong file... You were supposed to finish that file - https://github.com/serrhiy/database-course-work/blob/write-stakeholders-needs/docs/ua/requirements/stakeholders-needs.md
