### ISSUE TITLE
Lab1 : Write The State Of The Art

### ISSUE THREAD

**Issue by serrhiy** [serrhiy/database-course-work#23]
@ypapish you're in charge, assign tasks and get to work. Try to communicate in Issues.
Write documentation in Ukrainian at first, so work in the docs/ua directory

**Comment by serrhiy** [comment]
Don't forget to create separate branches under development, feel free to ask me for help

**Comment by ypapish** [comment]
@gothicenemy your part is ''Approaches and methods for solving the task''

**Comment by serrhiy** [comment]
@ypapish Perfect! But:
 1. it seems to me that ```Ми проаналізуємо оптимальні підходи...``` should be replaced with ```Проаналізовано оптимальні підходи...```;
 2. rewrite the intro a bit so that it doesn't look AI-generated (you can use examples from previous years).

**Comment by serrhiy** [comment]
@ypapish Format the document in a business style, do not use "we" or other pronouns. Use third-person narration. So not ```У цьому документі ми розглянули``` but ```У цьому документі розглянуто``` and not ```Ми проаналізували оптимальні підходи``` but ```Проаналізовано оптимальні підходи```. Everything else is fine, feel free to ask me questionons again

**Comment by ypapish** [comment]
@ruxudh your part is "Comparative characteristic of existing tools for solving the task"
